site_1:
  image: httpd:2.4
  restart: always
  expose:
    - "80"
  volumes:
    - /path/to/site-1:/usr/local/apache2/htdocs
site_2:
  image: httpd:2.4
  restart: always
  expose:
    - "80"
  volumes:
    - /path/to/site-2:/usr/local/apache2/htdocs
reverse-proxy:
  build: ./
  restart: always
  links:
    - site_1
    - site_2
  ports:
    - "80:80"
  volumes:
    - ./vhosts/000-default.conf:/etc/apache2/sites-available/000-default.conf
    - ./vhosts/site-1.conf:/etc/apache2/sites-available/site-1.conf
    - ./vhosts/site-2.conf:/etc/apache2/sites-available/site-2.conf
